//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Language12
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "Language12";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Language12";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID Language12DiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Language12CommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID Language12ExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Language12CommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewLanguage12ExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Language12CommandSetId), 0x0001);
	
		// Package identifier
		public const string Language12PackageId = "b3a9b4fc-34d3-4fc7-b521-433fc9af33bd";
		
		// Editor factory identifier
		public const string Language12EditorFactoryId = "03846049-b1f9-43df-bd6e-a03c26f928d4";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string Language12ModelExplorerToolWindowId = "88032ecc-bc09-4194-945c-d263d793e93b";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.Language12
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string Language12CommandSetId = "d10066fe-9cf8-4753-a5f7-d003d9d59e5f";
	}
}